name: Run Playwright to Like a TikTok Video

on:
  push:
    branches:
      - main

jobs:
  run_playwright:
    runs-on: ubuntu-latest

    steps:
      # Instalar dependências do Playwright e xvfb
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb

      # Instalar Playwright
      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install  # Instala navegadores necessários

      # Criar e executar o script do Playwright
      - name: Run Playwright Script
        run: |
          echo "const { chromium, devices } = require('playwright');" > script.js
          echo "const fs = require('fs');" >> script.js
          echo "const iPhone = devices['iPhone 12'];" >> script.js  # Define o dispositivo como iPhone 12
          echo "(async () => {" >> script.js
          echo "  for (let i = 0; i < 100; i++) {" >> script.js  # Loop para repetir a ação 100 vezes
          echo "    const browser = await chromium.launch({ headless: false });" >> script.js  # Mude para true para headless
          echo "    const context = await browser.newContext({ ...iPhone });" >> script.js  # Usando a simulação do iPhone
          echo "    const page = await context.newPage();" >> script.js

          # Navegar para a página do vídeo do TikTok
          echo "    await page.goto('https://www.tiktok.com/@gkzx7_/live?enter_from_merge=others_homepage&enter_method=others_photo');" >> script.js

          # Aguardar o carregamento da página do vídeo
          echo "    await page.waitForTimeout(99999);  // Aguarda 5 segundos para garantir que a página carregou" >> script.js

          # Esperar por um tempo para ver a ação
          echo "    await page.waitForTimeout(0);  // Aguarda 10 segundos para ver a interação" >> script.js
          echo "    await browser.close();" >> script.js
          echo "  }" >> script.js  # Fecha o loop
          echo "})();" >> script.js

          # Executa o script com xvfb
          xvfb-run -a node script.js  # Executa o script com xvfb
